server:
  port: 8080
database:
  host: 147.79.110.229
  port: 3306
  user: n8n_admin
  password: vinculaadmin2025
  name: vincula_latam
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m
log:
  level: info
